
spring:
  application:
    name: basicSample
    data:
    solr:
      host: http://${SOLR_CONTAINER_NAME:localhost}:8983/solr/
      repositories:
        enabled: false

  profiles:
    active: dev
    group:
      dev:
        - dev
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8082

#================================================================
#Logger
logging:
   #file:
    #path: logs
    #name: logs/dailylogs.log
    #max-history: '30'
    #max-size: 10MB
    
   pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS", UTC} [%thread] %-5level %-50logger{40} : %msg%n'
    #rolling-file-name: logs/dailylogs-%d{yyyy-MM-dd}.%i.log
   level:
    ROOT: DEBUG
    org.springframework.web: "error"
    org.hibernate: "error"
    org: "error"

#================================================================
#Swagger
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  documentation:
    auto-startup: false
#================================================================


#================================================================
#Solr Configurations
base-solr-url: http://${SOLR_CONTAINER_NAME:localhost}:8983/solr
#================================================================


#================================================================
#Capacity Plans
capacity-plan:
  plans:
    - sku: B
      name: Basic
      replicas: 1
      shards: 1
      storage: 2

    - sku: S1
      name: Standard
      replicas: 2
      shards: 2
      storage: 32

    - sku: S2
      name: Standard
      replicas: 2
      shards: 3
      storage: 32

    - sku: S3
      name: Standard
      replicas: 3
      shards: 7
      Storage: 32

    - sku: P
      name: Premium
      replicas: 3
      shards: 5
      storage: 2
#================================================================


#================================================================
# Throttler configurations
base-app-url: http://localhost:8082
throttler-test-app-url: http://localhost:8082
resilience4j.ratelimiter:
  instances:
    solrDataInjectionRateLimitThrottler:
      limitForPeriod: 3
      limitRefreshPeriod: 4s
      timeoutDuration: 1s
      eventConsumerBufferSize: 100
      registerHealthIndicator: true
    defaultRateLimitThrottler:
      limitForPeriod: 3
      limitRefreshPeriod: 5s
      timeoutDuration: 1s
      eventConsumerBufferSize: 100
      registerHealthIndicator: true
resilience4j:
  maxRequestSize:
    maxAllowedRequestSize: 10kB
throttle-service:
  solr:
    data-injection: solrDataInjectionRateLimitThrottler
  test: defaultRateLimitThrottler
#================================================================


# ConfigSet Configurations
base-configset: _default

# Solr authentication(basicAuth) credentials
basic-auth:
  username: solr
  password: SolrRocks
  

#================================================================
#Table schema soft delete sync
table-schema-attributes:
  delete-file-path: src\\main\\resources\\SchemaDeleteRecord.txt
#================================================================


#================================================================
#Sync with soft delete schema in microservice
base-microservice-url: http://localhost:8081
microservice-url:
  get-table: /api/v1/manage/table
#================================================================


#================================================================
#base-urls
base-url:
  api-endpoint:
    home: /search/api/v1

    
#================================================================
# Keycloak Server Configurations
keycloak:
  realm: Demo_Realm
  credentials: 
    secret: fkt2zezjwsvxd1YzyiKwJvqCv91HFBrW
  resource: saas-egress-microservice
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  public-client: false
  use-resource-role-mappings: true
#================================================================
