apiVersion: v1
kind: Service
metadata:
  name: search-service-egress-service
spec:
  selector:
    app: search-service-egress
  ports:
    - protocol: 'TCP'
      port: 8082
      targetPort: 8082
  type: LoadBalancer